"""Hapus kolom password

Revision ID: 0f4c2eb9e0fe
Revises: 4c8f02a6cc5a
Create Date: 2025-10-28 07:39:52.606097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4c2eb9e0fe'
down_revision = '4c8f02a6cc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
