"""Tambah Skema Ruangan dan RuanganUser

Revision ID: 15e3a17be3d4
Revises: 6d278d92961d
Create Date: 2025-10-28 07:52:23.405801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15e3a17be3d4'
down_revision = '6d278d92961d'
branch_labels = None
depends_on = None


ruangan_table = sa.table(
    'ruangan',
    sa.Column('id', sa.Integer),
    sa.Column('name', sa.String(length=50)),
)

ruangan_user_table = sa.table(
    'ruangan_user',
    sa.Column('id', sa.Integer),
    sa.Column('user_id', sa.Integer),
    sa.Column('ruangan_id', sa.Integer),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ruangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ruangan_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ruangan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ruangan_id'], ['ruangan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        ruangan_table,
        [
            {'id': 1, 'name': 'Lab Komputer'},
            {'id': 2, 'name': 'Ruang Rapat'},
            {'id': 3, 'name': 'Aula Serbaguna'},
        ],
    )

    op.bulk_insert(
        ruangan_user_table,
        [
            {'id': 1, 'user_id': 101, 'ruangan_id': 1},
            {'id': 2, 'user_id': 102, 'ruangan_id': 2},
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ruangan_user')
    op.drop_table('ruangan')
    # ### end Alembic commands ###
