"""Tambah kolom password

Revision ID: 4c8f02a6cc5a
Revises: d992cbd9f3ec
Create Date: 2025-10-28 07:38:11.296925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8f02a6cc5a'
down_revision = 'd992cbd9f3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
