"""Tambahkan kolom email ke User

Revision ID: d992cbd9f3ec
Revises: 4f3047030277
Create Date: 2025-10-28 07:36:53.340013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd992cbd9f3ec'
down_revision = '4f3047030277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
